const actions = {
  SET_STATE: 'audience/SET_STATE',
  CREATE_A_AUDIENCE: 'audience/CREATE_A_AUDIENCE',
  GET_AUDIENCE: 'audience/GET_AUDIENCE',
  GET_AUDIENCE_DETAIL: 'audience/GET_AUDIENCE_DETAIL',
  DELETE_AUDIENCE: 'audience/DELETE_AUDIENCE',
  GET_DEFINITION_AUDIENCE: 'audience/GET_DEFINITION_AUDIENCE',
  GET_AUDIENCE_SUBSCRIBERS: 'audience/GET_AUDIENCE_SUBSCRIBERS',
  REMOVE_SUBSCRIBER_OUT_OF_AUDIENCE: 'audience/REMOVE_SUBSCRIBER_OUT_OF_AUDIENCE',
}

export default actions
