const actions = {
  SET_STATE: 'subscriber/SET_STATE',
  GET_DATA_SUBSCRIBERS: 'subscriber/GET_DATA_SUBSCRIBERS',
  CREATE_A_SUBSCRIBER: 'subscriber/CREATE_A_SUBSCRIBER',
  LOAD_SUBSCRIBER_TYPES: 'subscriber/LOAD_SUBSCRIBER_TYPES',
  UPDATE_SUBSCRIBERS: 'subscriber/UPDATE_SUBSCRIBERS',
  DELETE_SUBSCRIBERS: 'subscriber/DELETE_SUBSCRIBERS',
  IMPORT_EXCEL_SUBSCRIBERS: 'subscriber/IMPORT_EXCEL_SUBSCRIBERS',
  MOVING_SUBSCRIBER_TO_AUDIENCE: 'subscriber/MOVING_SUBSCRIBER_TO_AUDIENCE',
  // LOAD_CURRENT_ACCOUNT: 'behavior/LOAD_CURRENT_ACCOUNT',
  UNSUBSCRIBE: 'subscriber/UNSUBSCRIBE',
}

export default actions
