const actions = {
  SET_STATE: 'campaign/SET_STATE',
  // CREATE_NEW_CAMPAIGN: 'campaign/CREATE_NEW_CAMPAIGN',
  SAVE_CAMPAIGN_NAME: 'campaign/SAVE_CAMPAIGN_NAME',
  EDIT_CAMPAIGN_NAME: 'campaign/EDIT_CAMPAIGN_NAME',
  CREATE_AUTOMATED_CAMPAIGNS: 'campaign/CREATE_AUTOMATED_CAMPAIGNS',
  GET_AUTOMATED_CAMPAIGN: 'campaign/GET_AUTOMATED_CAMPAIGN',
  START_STOP_CAMPAIGN: 'campaign/START_STOP_CAMPAIGN',
  GET_ALL_CAMPAIGNS: 'campaign/GET_ALL_CAMPAIGNS',
  DELETE_CAMPAIGNS: 'campaign/DELETE_CAMPAIGNS',
  UPDATE_CAMPAIGN: 'campaign/UPDATE_CAMPAIGN',
  GET_CAMPAIGN_BY_ID: 'campaign/GET_CAMPAIGN_BY_ID',
  CREATE_CAMPAIGN_AFTER_SAVE_NAME: 'campaign/CREATE_CAMPAIGN_AFTER_SAVE_NAME',
  START_STOP_AUTOMATION: 'campaign/START_STOP_AUTOMATION',
}

export default actions
