const actions = {
  SET_STATE: 'newsletter/SET_STATE',
  GET_NEWSLETTERS: 'newsletter/GET_NEWSLETTERS',
  GET_NEWSLETTER_BY_ID: 'newsletter/GET_NEWSLETTER_BY_ID',
  DELETE_NEWSLETTERS: 'newsletter/DELETE_NEWSLETTERS',
  CREATE_NEWSLETTER: 'newsletter/CREATE_NEWSLETTER',
  GET_NEWEST_NEWSLETTER: 'newsletter/GET_NEWEST_NEWSLETTER',
  CREATE_EMAIL: 'newsletter/CREATE_EMAIL',
  UPDATE_NEWSLETTER: 'newsletter/UPDATE_NEWSLETTER',
  SEND_MAIL: 'newsletter/SEND_MAIL',
  GET_ALL_AUDIENCE: 'newsletter/GET_ALL_AUDIENCE',
  UPDATE_NEWSLETTER_AUDIENCE: 'newsletter/UPDATE_NEWSLETTER_AUDIENCE',
}

export default actions
